name       : polyclipping
version    : 6.4.2
release    : 1
source     :
    - https://netix.dl.sourceforge.net/project/polyclipping/clipper_ver6.4.2.zip : a14320d82194807c4480ce59c98aa71cd4175a5156645c4e2b3edd330b930627
license    : BSL-1.0
component  : programming.library
summary    : Polygon and line clipping and offsetting library
description: |
    The Clipper library performs clipping and offsetting for both lines and polygons. All four boolean clipping operations are supported - intersection, union, difference and exclusive-or. Polygons can be of any shape including self-intersecting polygons.
setup      : |
    pushd cpp
        %cmake .
    popd
build      : |
    %make -C cpp
install    : |
    %make_install -C cpp
